title: Python Programming for Economics and Finance
author: Thomas J. Sargent & John Stachurski
logo: _static/qe-logo-large.png
keywords: Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski
description: This website presents a set of lectures on python programming for economics, designed and written by Thomas J. Sargent and John Stachurski

twitter: quantecon
twitter_logo_url: https://assets.quantecon.org/img/qe-twitter-logo.png
og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png

execute:
  execute_notebooks: "cache"
  timeout: 60
#   run_in_temp: true

sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinx_exercise]
  config:
    html_logo: _static/qe-logo.png
    html_favicon: _static/qe-logo.png
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    html_theme_options:
      header_organisation_url: https://quantecon.org
      header_organisation: QuantEcon
      google_analytics_id: UA-54984338-9
